image: node:latest

variables:
  POSTGRES_HOST: postgres
  POSTGRES_DB: brute_pg
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ""

services:
  - postgres:latest

test:
  before_script:
    - apt-get update && apt-get install -y postgresql-client
    - psql -h postgres -U postgres brute_pg -c "create table brute(id text primary key, count int, first_request timestamptz, last_request timestamptz, expires timestamptz);"
  script:
    - npm i
    - npm test
