language: node_js
node_js:
    - "0.12.18"
    - "4"
    - "5"
    - "6"
addons:
    postgresql: "9.4"
before_script:
    - psql -c 'create database brute_pg;' -U postgres
    - psql -c "create table brute(id text primary key, count int, first_request timestamptz, last_request timestamptz, expires timestamptz);" brute_pg -U postgres
